### ISSUE TITLE
[ci] Failing fuzz tests on master (30 Aug 2022)

### ISSUE THREAD

**Issue by paritytech-cicd-pr** [paritytech/ink#1375] opened 2022-08-30 21:07 UTC
The CI job [1791234](https://gitlab.parity.io/parity/mirrors/ink/-/jobs/1791234) just failed.

The offending commit is [Fix CI (#1373)](https://github.com/paritytech/ink/commit/d535ba78b05ed81985dd314f33f88424fd5c660d).

**Comment by cmichi** [comment] 2022-08-31 06:00
Duplicate of https://github.com/paritytech/ink/issues/1374.

**Closed by cmichi** 2022-08-31 06:00 UTC
