### ISSUE TITLE
AccountId flush Error

### ISSUE THREAD

**Issue by sunqiLoveSnow** [paritytech/ink#152] opened 2019-07-26 09:46 UTC
*** Source code:
```
#![cfg_attr(not(any(test, feature = "std")), no_std)]

use ink_core::{
    memory::format,
    storage,
};
use ink_lang::contract;

contract! {
    #![env = ink_core::env::DefaultSrmlTypes]

    /// This simple dummy contract has a `bool` value that can
    /// alter between `true` and `false` using the `flip` message.
    /// Users can retrieve its current state using the `get` message.
    struct Flipper {
        /// The current state of our flag.
        value: storage::Value<bool>,
        b : storage::Value<Balance>,
        // b : Balance,
        va : storage::Value<AccountId>,
        // va : AccountId,
        // ha : storage::HashMap<AccountId, u64>,
    }

    impl Deploy for Flipper {
        /// Initializes our state to `false` upon deploying our smart contract.
        fn deploy(&mut self) {
            self.value.set(false)
        }
    }

    impl Flipper {
    }
}

#[cfg(all(test, feature = "test-env"))]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
    }
}
```
*** Error Message:

error[E0599]: no method named `flush` found for type `ink_core::storage::value::Value<ink_core::env::srml::types::AccountId>` in the current scope
  --> src/lib.rs:9:1
   |
9  | / contract! {
10 | |     #![env = ink_core::env::DefaultSrmlTypes]
11 | |
12 | |     /// This simple dummy contract has a `bool` value that can
...  |
33 | |     }
34 | | }
   | |_^
   |
   = note: the method `flush` exists but the following trait bounds were not satisfied:
           `ink_core::storage::value::Value<ink_core::env::srml::types::AccountId> : ink_core::storage::flush::Flush`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `flipper`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name flipper src/lib.rs --color always --emit=dep-info,link -C debuginfo=2 --test --cfg 'feature="default"' --cfg 'feature="test-env"' -C metadata=aa75f0265ae87a7d -C extra-filename=-aa75f0265ae87a7d --out-dir /mnt/d/ubuntu/ink/test_fli/target/debug/deps -C incremental=/mnt/d/ubuntu/ink/test_fli/target/debug/incremental -L dependency=/mnt/d/ubuntu/ink/test_fli/target/debug/deps --extern ink_core=/mnt/d/ubuntu/ink/test_fli/target/debug/deps/libink_core-0f5e8b8b13f6c77d.rlib --extern ink_lang=/mnt/d/ubuntu/ink/test_fli/target/debug/deps/libink_lang-126c59833582ea8b.so --extern ink_model=/mnt/d/ubuntu/ink/test_fli/target/debug/deps/libink_model-743e2ae26e8cc13a.rlib --extern parity_codec=/mnt/d/ubuntu/ink/test_fli/target/debug/deps/libparity_codec-1a736c8ab44306b6.rlib` (exit code: 1)

**Comment by sunqiLoveSnow** [comment] 2019-07-26 09:47
here's my lib.rs:

#![cfg_attr(not(any(test, feature = "std")), no_std)]

use ink_core::{
    memory::format,
    storage,
};
use ink_lang::contract;

contract! {
    #![env = ink_core::env::DefaultSrmlTypes]

    /// This simple dummy contract has a `bool` value that can
    /// alter between `true` and `false` using the `flip` message.
    /// Users can retrieve its current state using the `get` message.
    struct Flipper {
        /// The current state of our flag.
        value: storage::Value<bool>,
        b : storage::Value<Balance>,
        // b : Balance,
        va : storage::Value<AccountId>,
        // va : AccountId,
        // ha : storage::HashMap<AccountId, u64>,
    }

    impl Deploy for Flipper {
        /// Initializes our state to `false` upon deploying our smart contract.
        fn deploy(&mut self) {
            self.value.set(false)
        }
    }

    impl Flipper {
    }
}

#[cfg(all(test, feature = "test-env"))]
mod tests {
    use super::*;

    #[test]
    fn it_works() {
    }
}

**Comment by Robbepop** [comment] 2019-07-26 10:29
Thanks for reporting!
We will fix this asap.

**Comment by flyq** [comment] 2019-07-26 13:15
the code of [commit 7d19156e](https://github.com/paritytech/ink/tree/7d19156eede9dd2f5e2e58c13302707c1f89fe2f) works well, so maybe the problem is in  [commit 7948d23b](https://github.com/paritytech/ink/commit/7948d23b6fcdd39d21a48061efd5d82813ceaabb)
![image](https://user-images.githubusercontent.com/16486808/61953737-c478c280-afe9-11e9-9d00-9d9200aab31d.png)

**Comment by Robbepop** [comment] 2019-07-26 14:28
@flyq have you also checked already if [this PR](https://github.com/paritytech/ink/pull/151) fixes your problem?

**Comment by flyq** [comment] 2019-07-27 01:27
> @flyq have you also checked already if [this PR](https://github.com/paritytech/ink/pull/151) fixes your problem?

I will try [this PR 151](https://github.com/paritytech/ink/pull/151) today.

Yesterday, I finded there are two kinds of bugs:
one is event:
```bash
error[E0277]: the trait bound `ink_core::env::srml::types::AccountId: events::_IMPL_DECODE_FOR_Approval::_parity_codec::Decode` is not satisfied
   --> src/lib.rs:10:1
    |
10  | / contract! {
11  | |     #![env = DefaultSrmlTypes]
12  | |
13  | |     event Transfer {
...   |
129 | |     }
130 | | }
    | |_^ the trait `events::_IMPL_DECODE_FOR_Approval::_parity_codec::Decode` is not implemented for `ink_core::env::srml::types::AccountId`
    |
    = note: required by `events::_IMPL_DECODE_FOR_Approval::_parity_codec::Decode::decode`
```
this is caused by [commit 7948d23b](https://github.com/paritytech/ink/commit/7948d23b6fcdd39d21a48061efd5d82813ceaabb), and deleting some modifications of Cargo.toml fixes this.


another is hashmap:
```bash
error[E0599]: no method named `flush` found for type `ink_core::storage::collections::hash_map::impls::HashMap<ink_core::env::srml::types::AccountId, u64>` in the current scope
   --> src/lib.rs:10:1
    |
10  | / contract! {
11  | |     #![env = DefaultSrmlTypes]
12  | |
13  | |     event Transfer {
...   |
129 | |     }
130 | | }
    | |_^
    |
    = note: the method `flush` exists but the following trait bounds were not satisfied:
            `ink_core::storage::collections::hash_map::impls::HashMap<ink_core::env::srml::types::AccountId, u64> : ink_core::storage::flush::Flush`
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```
this is caused by [commit b66ab319](https://github.com/paritytech/ink/commit/b66ab319e1aff024a658e48e41038f075965b25b), and I don't know how to fix it.

**Comment by flyq** [comment] 2019-07-27 03:06
> @flyq have you also checked already if [this PR](https://github.com/paritytech/ink/pull/151) fixes your problem?

I checked just now, [this PR 151](https://github.com/paritytech/ink/pull/151) fixes the `flush` problem of `hashmap`.

and rolling back the version of parity-codec fixes the `event` problem.

the more is here:
https://github.com/paritytech/ink/pull/154

![image](https://user-images.githubusercontent.com/16486808/61989211-7baf2100-b05e-11e9-96b3-53bf22efaf4e.png)

**Comment by Robbepop** [comment] 2019-07-27 07:04
I would not appreciate rolling back to parity-codec 3.2 unless it is the only fix we can do.
The event bug should also be fixed by the PR.

**Comment by flyq** [comment] 2019-07-27 07:44
> I would not appreciate rolling back to parity-codec 3.2 unless it is the only fix we can do.
> The event bug should also be fixed by the PR.

Yeah, cool, expecting the better way.

**Comment by Robbepop** [comment] 2019-07-30 10:55
Is this fixed now with the PRs merged?

**Comment by flyq** [comment] 2019-07-31 14:53
Yes, if running `cargo install --force --git https://github.com/paritytech/ink cargo-contract` to update the `cargo-contract`, and everything is ok.

**Closed** 2019-07-31 15:03 UTC
Labels: A-ink_core, C-bug
