### ISSUE TITLE
The generated abi.json format is incorrect

### ISSUE THREAD

**Issue by jeremymj** [paritytech/ink#222] opened 2019-11-05 12:49 UTC
Create a contract with the latest version ‘b0429dea376e21cd24cdaa8fb8e3d43bc44c8924’,use command `cargo contract new apptest`,and generated the
 [abi.json](https://github.com/paritytech/ink/files/3808967/abi.txt) file with command `cargo +nightly run -p abi-gen`,upload the abi.json file in the [UI interface](https://polkadot.js.org/apps/#/contracts/code), and a format error message appears. 
![Screenshot from 2019-11-05 20-40-42](https://user-images.githubusercontent.com/13585788/68208662-9f461800-000c-11ea-81b0-a9defb52deab.png)
The contract in the example directory of the ink project can be uploaded normally.

**Comment by Robbepop** [comment] 2019-11-05 12:59
Hey, we are aware of that issue and are trying to fix the root cause.
Thanks nonetheless for posting this!

**Comment by Robbepop** [comment] 2019-11-05 13:48
To add a bit of information. In the `types` section of the ABI there are duplicates concerning `TestEnv` or `SrmlEnv` respectively. And one of those duplicates is invalidly marked as `builtin`. Note though, that there should be no duplicates in any of the tables to start with. The problem happens because there seem to be types that have different `core::any::TypeId` but the same `ink_abi::TypeId`.

**Comment by jeremymj** [comment] 2019-11-06 01:37
Ok, I will modify my file to bypass this problem. Looking forward to your update.

**Comment by Robbepop** [comment] 2019-11-14 14:49
Fixed. Closed.

**Closed by Robbepop** 2019-11-14 14:49 UTC
Labels: A-ink_abi, C-bug
