### ISSUE TITLE
Implement storage::Map::entry API

### ISSUE THREAD

**Issue by usd-yamazaki** [paritytech/ink#112] opened 2019-06-04 09:20 UTC
In order to use HashMap more like Rust, please make Entry public and implement or_insert.

Link to Rust's `BTreeMap` `Entry` API: https://doc.rust-lang.org/std/collections/btree_map/enum.Entry.html

We really want this API for ergonomics and it should be possible to have all the lifetime-safety guarantees that Rust's API brings with it, even though we are operating on storage instead of memory.

**Comment by Robbepop** [comment] 2020-05-20 12:23
Duplicate of https://github.com/paritytech/ink/issues/379.

**Closed by Robbepop** 2020-05-20 12:23 UTC
Labels: A-ink_core, B-enhancement
