### ISSUE TITLE
[ci] Failing fuzz tests on master (21 Jul 2022)

### ISSUE THREAD

**Issue by paritytech-cicd-pr** [paritytech/ink#1333] opened 2022-07-21 06:07 UTC
The CI job [1689607](https://gitlab.parity.io/parity/mirrors/ink/-/jobs/1689607) just failed.

The offending commit is [Update test fixtures (#1328)](https://github.com/paritytech/ink/commit/7e637a351b1684995da472090c505cb2daf49e36).

**Comment by HCastano** [comment] 2022-07-21 15:36
Duplicate of #1323

**Closed by HCastano** 2022-07-21 15:36 UTC
