### ISSUE TITLE
[rc8] examples/erc721 build upload/deployment fails with `ContractTrapped`

### ISSUE THREAD

**Issue by agryaznov** [paritytech/ink#1108] opened 2022-01-22 13:32 UTC
This error appears during uploading the contract through PolkadotJS Apps, however, it does not seem to be UI related, as it is clear that _DispatchError_ is being returned from runtime: 
```
Module: {
    index: 8
    error: 10
  }
```
(which is `ContractTrapped` from `pallet_contracts`)

**The bug**

[_examples/erc721_](https://github.com/paritytech/ink/tree/v3.0.0-rc8/examples/erc721) contract taken from [ink! v3.0.0-rc8](https://github.com/paritytech/ink/releases/tag/v3.0.0-rc8) **builds successfully** with [_cargo-contract 0.17_](https://github.com/paritytech/cargo-contract/releases/tag/v0.17.0)

Uploading that build through _PolkadotJS Apps v0.102.2_ connected to [_substrate-contracts-node v0.5.0_](https://github.com/paritytech/substrate-contracts-node/releases/tag/v0.5.0) **fails** with `ContractTrapped`

**Comment by xgreenx** [comment] 2022-01-23 10:18
After the https://github.com/paritytech/ink/pull/1065, the constructor should be payable to be able to get a deposit for a contract.
<img width="668" alt="image" src="https://user-images.githubusercontent.com/18346821/150673745-1abdc564-f810-4b9c-9790-9ede78cc37d1.png">


@cmichi @athei Hmm, seems that the transferred balance will be always not zero during the instantiation of the contract. When constructor can be not payable? Maybe `contract-pallet` should subtract the deposit(minimum balance) from transferred value during instantiation?

**Comment by athei** [comment] 2022-01-24 09:02
With the new automatic storage deposits we don't use the the transferred value in order to have the minimum balance. What will happen is that the required deposit is automatically transferred to the contracts account and is reserved there.

This is what allows us to have non payable constructors: The minimum deposit is handled by the pallet and the transferred value is only needed (or allowed) to be non zero if the contract logic requires it (payable constructor). Essentially constructors and messages behave exactly the same there now.

**Comment by athei** [comment] 2022-01-24 15:50
Just tested with everything on master and apps v0.103.1. Deploy works for me. What did you enter as `value`?

**Comment by cmichi** [comment] 2022-01-24 17:04
@agryaznov I also can't reproduce the error. I installed `substrate-contracts-node` with `--locked`.

**Comment by agryaznov** [comment] 2022-01-24 17:13
The `value` was set to `1000` during deployment, which seems to be the reason of `ContractTrapped` as _ERC721_ constructor became non-payable by default (after storage deposits introduced with [#10082](https://github.com/paritytech/substrate/pull/10082) PR)... 

With `value` = `0` the contract is being deployed successfully.

I think this will be an often mistake made by users who would likely specify non-zero ~endowment~ `value` on contract deployment, just on habit of a way how it used to work before.

**Comment by HCastano** [comment] 2022-01-24 17:59
> With `value` = `0` the contract is being deployed successfully.
> 
> I think this will be an often mistake made by users who would likely specify non-zero ~endowment~ `value` on contract deployment, just on habit of a way how it used to work before.

This won't be a problem in the future with https://github.com/polkadot-js/apps/issues/6645. The UI won't show the `value` field if a constructor isn't marked explicitly as `payable`.

**Closed** 2022-01-24 18:00 UTC

**Comment by xgreenx** [comment] 2022-01-24 19:27
When I'm submitting the transaction about deployment with `value` zero it throw an `contracts.NewContractNotFunded`.
If I set the value 1 dot, it fails with contract trapped because the constructor is not `payable`. How do I need to instantiate the contract and pass 1 dot as endowment?

**Comment by athei** [comment] 2022-01-24 19:48
That can't be because this error doesn't exist anymore. So you are most likely testing against an older node than you think you are.

**Comment by xgreenx** [comment] 2022-01-24 20:58
> That can't be because this error doesn't exist anymore. So you are most likely testing against an older node than you think you are.

Yep, you are right, I had two nodes at the same time. With a new one everything works
