### ISSUE TITLE
Message arguments cannot be destructured 

### ISSUE THREAD

**Issue by KaiserKarel** [paritytech/ink#818] opened 2021-06-16 13:01 UTC
`pub fn foo(&mut self, Bar { baz, bax }: Bar) `

In regular Rust, function arguments may be restructured like so, but the ink macro will error:

```
error: custom attribute panicked
  --> contracts/pod-media/src/lib.rs:11:1
   |
11 | #[ink::contract]
   | ^^^^^^^^^^^^^^^^
   |
   = help: message: internal error: entered unreachable code: encountered unexpected non identifier in ink! parameter
```

**Comment by Robbepop** [comment] 2021-06-16 13:03
We might be able to implement this. Thanks for letting us know that support for Rust patterns in message parameters is needed. :)

**Comment by KaiserKarel** [comment] 2021-06-16 13:10
I reckoned that we want to keep `ink!` as close as possible to real rust. :) Although I don't think that rust patters are used often like this, from time to time it is nice to have.

If one can point me to where this can be implemented, I can try to create a PR myself

**Comment by Robbepop** [comment] 2021-06-16 13:14
Implementation of ink! analysis is found in `crates/lang/ir` and codegen is in `crates/lang/codegen`. A PR probably needs to touch both given that we have the unwanted behavior for non-identifier parameters in ink! messages which probably resides in `crates/lang/ir`. The problem is that you really need to know where to touch things because in some positions we want to keep generating identifiers instead of patterns.

**Comment by KaiserKarel** [comment] 2021-06-16 13:43
I assume that there are the steps that need to be implemented:

- Add pattern to AST
- Add definition of pattern to ir

**Comment by HCastano** [comment] 2021-06-16 16:53
I don't think I've ever seen struct destructuring used for function parameters before, TIL!

**Comment by Robbepop** [comment] 2021-06-17 11:59
> I assume that there are the steps that need to be implemented:
> 
>     * Allow for patterns in IR: ([section](https://github.com/paritytech/ink/blob/e1486563d9cf3a0ab3154686a989cd88aca579d1/crates/lang/codegen/src/generator/metadata.rs#L171))

Indeed metadata generation will require you to provide an actual identifier for the purpose of serialization in this case.
So if we were to implement destructible message parameters we would also be required to add a new ink! specific parmeter attribute `#[ink(name = "foo")]` in order to tell ink! what name this pattern has which probably undermines the whole point of this feature slightly.

**Comment by KaiserKarel** [comment] 2021-06-21 12:38
Yeah, the whole point was saving 1 LOC ;). I'll probably change the error message then. Perhaps add an explanation and reference to this issue?

**Comment by Robbepop** [comment] 2021-06-21 12:42
Yep, I now too think that not allowing patterns for message or constructor parameters simplifies ink! design.
You could still do the destructuring of the parameter in the message or constructor body.

Can we close this issue therefore?

**Comment by KaiserKarel** [comment] 2021-07-05 21:00
Shall I open up a PR associated with this issue to improve the error message?

**Comment by Robbepop** [comment] 2021-07-06 08:42
> Shall I open up a PR associated with this issue to improve the error message?

I would appreciate this!

**Comment by Robbepop** [comment] 2021-09-12 11:32
I think this can be closed. Please re-open if you think there is work left.

**Closed by Robbepop** 2021-09-12 11:32 UTC
Labels: A-ink_lang, B-feature-request
