### ISSUE TITLE
ContractRef objects don't implement `SpreadAllocate` trait.

### ISSUE THREAD

**Issue by drewstone** [paritytech/ink#1149] opened 2022-02-27 20:39 UTC
# Overview
I'm trying to initialize a contract that holds both `Mapping`s and `ContractRef`s to other contracts. It does not seem that contract references by default implement the necessary trait and as such I cannot compile these contracts. Is there a recommended method for init'ing contracts with these items side by side?

**Comment by HCastano** [comment] 2022-03-01 01:40
I saw that you and @xgreenx had some discussions about this on Element. Do you mind re-posting any important bits from there here?

Can you also post a link to the contracts so that we can reproduce this.

**Comment by xgreenx** [comment] 2022-03-01 07:11
The problem is that `ContractRef` and `CallBuilder` generated by [codegen doesn't implement `SpreadAllocate`](https://github.com/paritytech/ink/blob/master/crates/lang/codegen/src/generator/as_dependency/contract_ref.rs#L93).

As a workaround, the user can implement `SpreadAllocate` manually current contract or the user can use `AccountId` instead of `ContractRef`(under the hood it is account id).

Also if the user has the source of the `Contract`, he can implement `SpreadAllocate` manually for `ContractRef`.

```rust
impl SpreadAllocate for ContractRef {
    fn allocate_spread(_ptr: &mut ink_primitives::KeyPtr) -> Self {
        FromAccountId::from_account_id([0; 32].into())
    }
}
```

**Comment by cmichi** [comment] 2023-02-17 18:56
Closing, as we removed anything `SpreadLayout` for ink! 4.0.

**Closed by cmichi** 2023-02-17 18:56 UTC
Labels: C-bug, B-enhancement, P-low
