### ISSUE TITLE
Add #[ink(test)] proc. macro

### ISSUE THREAD

**Issue by Robbepop** [paritytech/ink#335] opened 2020-02-28 09:42 UTC
Currently contract writers have to wrap their test-cases with the `ink_core::env::test::run_test` API which creates another indentation.
Also this feature might evolve or change in the future.
What we really want/need is a proc. macro `#[ink(test)]` that always handles ink! test cases in a way that is appropriate for the current version so that users can focus on the task of writing tests with the normal test interface used by Rust.

**Comment by cmichi** [comment] 2020-09-22 07:56
Duplicate of #486.

**Closed by cmichi** 2020-09-22 07:56 UTC
