### ISSUE TITLE
[ci] Failing fuzz tests on master (01 Sep 2022)

### ISSUE THREAD

**Issue by paritytech-cicd-pr** [paritytech/ink#1378] opened 2022-09-01 06:07 UTC
The CI job [1796973](https://gitlab.parity.io/parity/mirrors/ink/-/jobs/1796973) just failed.

The offending commit is [Add `Eq` + `PartialEq` derive for `MetadataVersion` (#1377)](https://github.com/paritytech/ink/commit/8fce8f30577e03eb02ce666f7e63f194c5fd26ac).

**Comment by cmichi** [comment] 2022-09-01 10:00
Duplicate of https://github.com/paritytech/ink/issues/1374.

**Closed by cmichi** 2022-09-01 10:00 UTC
